//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarmentWear
    {
        public int GarmentWear_ID { get; set; }
        public Nullable<int> Garment_ID { get; set; }
        public Nullable<int> Wear_ID { get; set; }
    
        public virtual Garment Garment { get; set; }
        public virtual Wears Wears { get; set; }
    }
}
