//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class b8041046Entities : DbContext
    {
        public b8041046Entities()
            : base("name=b8041046Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Garment> Garment { get; set; }
        public virtual DbSet<GarmentOutfit> GarmentOutfit { get; set; }
        public virtual DbSet<GarmentWear> GarmentWear { get; set; }
        public virtual DbSet<Outfit> Outfit { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Wears> Wears { get; set; }
    }
}
